################################################################
## Sensor / Network Devices
################################################################

- platform: template
  sensors:
    aladdin_connect:
      value_template: "{{ 'online' if is_state('device_tracker.aladdin_connect', 'home') else 'offline' }}"
      entity_id: device_tracker.aladdin_connect
      warnings: false
