################################################################
## Sensor / System
################################################################

- platform: time_date
  display_options:
    - date
    - time
