################################################################
## Automation / Telegram Bot
################################################################

- alias: Roll a Die
  trigger:
    - platform: event
      event_type: incoming_bot_message
      event_data:
        text: '/roll'
  action:
    - service: notify.telegram
      data_template:
        title: ''
        message: "I rolled a die and got {{ [1, 2, 3, 4, 5, 6]|random }}."
